### ISSUE TITLE
DO NOT RUN

### ISSUE THREAD

**Issue by Hail2Hydra** [Ransomwarehelp/tiktokfollowbot#2]
https://www.virustotal.com/gui/file/4e32aef6a45bc466ede3e3aa998f31ab8d08964a59a8191c14827c12c8540a6d

drops a horribly hidden back door XD

**Comment by STATICWYD** [comment]
THANKS, I WAS ABOUT TO RUN

**Comment by Di3gorios** [comment]
thanks same
